version: '2'

services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: nginx-proxy
    ports:
      - "80:80"
  web:
    image: httpd
    volumes:
      - ./html:/usr/local/apache2/htdocs/